### ISSUE TITLE
Dígito de control no es válido para RFC RDE7910023J3

### ISSUE THREAD

**Issue by guillenjsa** [manuelmhtr/validate-rfc#31]
El RFC es válido y activo, como lo puede ver en el [Registro LEI](https://www.codigolei.mx/leicert/549300V8OI6WRAYEPG65/); sin embargo, la librería nos está retornando el siguiente objeto

`{ 
  isValid: false, 
  rfc: null, 
  typo: null, 
  errores: ['INVALID_VERIFICATION_DIGIT'] 
}`

Esperamos que lo pueda revisar. Slds

**Comment by manuelmhtr** [comment]
Hola @guillenjsa este es un problema conocido, está reportado en #https://github.com/manuelmhtr/validate-rfc/issues/24
y también en el [README](https://github.com/manuelmhtr/validate-rfc#check-digit-mismatches). Ya confirmé que el RFC `RDE7910023J3` es válido, por lo que paso a agregarlo a lista de RFCs validados tan pronto como sea posible.
